version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: infrastructure/docker/fpm/Dockerfile
    restart: unless-stopped
    volumes:
      - ./:/var/www
    networks:
      - phpdocker
  web:
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./infrastructure/docker/nginx/content/etc/conf.d:/etc/nginx/conf.d
    networks:
      - phpdocker
  db:
    image: mariadb:10.4
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./infrastructure/mysql:/docker-entrypoint-initdb.d
    networks:
      - phpdocker
networks:
  phpdocker:
